import type { Config } from 'tailwindcss';

/** @type {import('tailwindcss').Config} */
const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      safelist: [
        {
          pattern:
            /(bg|border)-(violet|gold|bronze|brown|yellow|amber|orange|tomato|red|ruby|crimson|pink|plum|purple|iris|indigo|blue|cyan|teal|jade|green|grass|lime|mint|sky)-(1|2|3|4|5|6)/,
        },
      ],
      screens: {
        '-2xl': { max: '1535px' },
        '-xl': { max: '1279px' },
        '-lg': { max: '1023px' },
        '-md': { max: '767px' },
        '-sm': { max: '639px' },
        '+maxH': { raw: '(max-height: 500px)' },
      },
      colors: {
        primary: {
          1: 'var(--primary-1)',
          2: 'var(--primary-2)',
          3: 'var(--primary-3)',
          4: 'var(--primary-4)',
          5: 'var(--primary-5)',
          6: 'var(--primary-6)',
          7: 'var(--primary-7)',
          8: 'var(--primary-8)',
          9: 'var(--primary-9)',
          10: 'var(--primary-10)',
          11: 'var(--primary-11)',
          12: 'var(--primary-12)',
        },
        gold: {
          1: 'var(--gold-1)',
          2: 'var(--gold-2)',
          3: 'var(--gold-3)',
          4: 'var(--gold-4)',
          5: 'var(--gold-5)',
          6: 'var(--gold-6)',
          7: 'var(--gold-7)',
          8: 'var(--gold-8)',
          9: 'var(--gold-9)',
          10: 'var(--gold-10)',
          11: 'var(--gold-11)',
          12: 'var(--gold-12)',
        },
        bronze: {
          1: 'var(--bronze-1)',
          2: 'var(--bronze-2)',
          3: 'var(--bronze-3)',
          4: 'var(--bronze-4)',
          5: 'var(--bronze-5)',
          6: 'var(--bronze-6)',
          7: 'var(--bronze-7)',
          8: 'var(--bronze-8)',
          9: 'var(--bronze-9)',
          10: 'var(--bronze-10)',
          11: 'var(--bronze-11)',
          12: 'var(--bronze-12)',
        },
        brown: {
          1: 'var(--brown-1)',
          2: 'var(--brown-2)',
          3: 'var(--brown-3)',
          4: 'var(--brown-4)',
          5: 'var(--brown-5)',
          6: 'var(--brown-6)',
          7: 'var(--brown-7)',
          8: 'var(--brown-8)',
          9: 'var(--brown-9)',
          10: 'var(--brown-10)',
          11: 'var(--brown-11)',
          12: 'var(--brown-12)',
        },
        yellow: {
          1: 'var(--yellow-1)',
          2: 'var(--yellow-2)',
          3: 'var(--yellow-3)',
          4: 'var(--yellow-4)',
          5: 'var(--yellow-5)',
          6: 'var(--yellow-6)',
          7: 'var(--yellow-7)',
          8: 'var(--yellow-8)',
          9: 'var(--yellow-9)',
          10: 'var(--yellow-10)',
          11: 'var(--yellow-11)',
          12: 'var(--yellow-12)',
        },
        amber: {
          1: 'var(--amber-1)',
          2: 'var(--amber-2)',
          3: 'var(--amber-3)',
          4: 'var(--amber-4)',
          5: 'var(--amber-5)',
          6: 'var(--amber-6)',
          7: 'var(--amber-7)',
          8: 'var(--amber-8)',
          9: 'var(--amber-9)',
          10: 'var(--amber-10)',
          11: 'var(--amber-11)',
          12: 'var(--amber-12)',
        },
        orange: {
          1: 'var(--orange-1)',
          2: 'var(--orange-2)',
          3: 'var(--orange-3)',
          4: 'var(--orange-4)',
          5: 'var(--orange-5)',
          6: 'var(--orange-6)',
          7: 'var(--orange-7)',
          8: 'var(--orange-8)',
          9: 'var(--orange-9)',
          10: 'var(--orange-10)',
          11: 'var(--orange-11)',
          12: 'var(--orange-12)',
        },
        tomato: {
          1: 'var(--tomato-1)',
          2: 'var(--tomato-2)',
          3: 'var(--tomato-3)',
          4: 'var(--tomato-4)',
          5: 'var(--tomato-5)',
          6: 'var(--tomato-6)',
          7: 'var(--tomato-7)',
          8: 'var(--tomato-8)',
          9: 'var(--tomato-9)',
          10: 'var(--tomato-10)',
          11: 'var(--tomato-11)',
          12: 'var(--tomato-12)',
        },
        red: {
          1: 'var(--red-1)',
          2: 'var(--red-2)',
          3: 'var(--red-3)',
          4: 'var(--red-4)',
          5: 'var(--red-5)',
          6: 'var(--red-6)',
          7: 'var(--red-7)',
          8: 'var(--red-8)',
          9: 'var(--red-9)',
          10: 'var(--red-10)',
          11: 'var(--red-11)',
          12: 'var(--red-12)',
        },
        ruby: {
          1: 'var(--ruby-1)',
          2: 'var(--ruby-2)',
          3: 'var(--ruby-3)',
          4: 'var(--ruby-4)',
          5: 'var(--ruby-5)',
          6: 'var(--ruby-6)',
          7: 'var(--ruby-7)',
          8: 'var(--ruby-8)',
          9: 'var(--ruby-9)',
          10: 'var(--ruby-10)',
          11: 'var(--ruby-11)',
          12: 'var(--ruby-12)',
        },
        crimson: {
          1: 'var(--crimson-1)',
          2: 'var(--crimson-2)',
          3: 'var(--crimson-3)',
          4: 'var(--crimson-4)',
          5: 'var(--crimson-5)',
          6: 'var(--crimson-6)',
          7: 'var(--crimson-7)',
          8: 'var(--crimson-8)',
          9: 'var(--crimson-9)',
          10: 'var(--crimson-10)',
          11: 'var(--crimson-11)',
          12: 'var(--crimson-12)',
        },
        pink: {
          1: 'var(--pink-1)',
          2: 'var(--pink-2)',
          3: 'var(--pink-3)',
          4: 'var(--pink-4)',
          5: 'var(--pink-5)',
          6: 'var(--pink-6)',
          7: 'var(--pink-7)',
          8: 'var(--pink-8)',
          9: 'var(--pink-9)',
          10: 'var(--pink-10)',
          11: 'var(--pink-11)',
          12: 'var(--pink-12)',
        },
        plum: {
          1: 'var(--plum-1)',
          2: 'var(--plum-2)',
          3: 'var(--plum-3)',
          4: 'var(--plum-4)',
          5: 'var(--plum-5)',
          6: 'var(--plum-6)',
          7: 'var(--plum-7)',
          8: 'var(--plum-8)',
          9: 'var(--plum-9)',
          10: 'var(--plum-10)',
          11: 'var(--plum-11)',
          12: 'var(--plum-12)',
        },
        purple: {
          1: 'var(--purple-1)',
          2: 'var(--purple-2)',
          3: 'var(--purple-3)',
          4: 'var(--purple-4)',
          5: 'var(--purple-5)',
          6: 'var(--purple-6)',
          7: 'var(--purple-7)',
          8: 'var(--purple-8)',
          9: 'var(--purple-9)',
          10: 'var(--purple-10)',
          11: 'var(--purple-11)',
          12: 'var(--purple-12)',
        },
        iris: {
          1: 'var(--iris-1)',
          2: 'var(--iris-2)',
          3: 'var(--iris-3)',
          4: 'var(--iris-4)',
          5: 'var(--iris-5)',
          6: 'var(--iris-6)',
          7: 'var(--iris-7)',
          8: 'var(--iris-8)',
          9: 'var(--iris-9)',
          10: 'var(--iris-10)',
          11: 'var(--iris-11)',
          12: 'var(--iris-12)',
        },
        indigo: {
          1: 'var(--indigo-1)',
          2: 'var(--indigo-2)',
          3: 'var(--indigo-3)',
          4: 'var(--indigo-4)',
          5: 'var(--indigo-5)',
          6: 'var(--indigo-6)',
          7: 'var(--indigo-7)',
          8: 'var(--indigo-8)',
          9: 'var(--indigo-9)',
          10: 'var(--indigo-10)',
          11: 'var(--indigo-11)',
          12: 'var(--indigo-12)',
        },
        blue: {
          1: 'var(--blue-1)',
          2: 'var(--blue-2)',
          3: 'var(--blue-3)',
          4: 'var(--blue-4)',
          5: 'var(--blue-5)',
          6: 'var(--blue-6)',
          7: 'var(--blue-7)',
          8: 'var(--blue-8)',
          9: 'var(--blue-9)',
          10: 'var(--blue-10)',
          11: 'var(--blue-11)',
          12: 'var(--blue-12)',
        },
        cyan: {
          1: 'var(--cyan-1)',
          2: 'var(--cyan-2)',
          3: 'var(--cyan-3)',
          4: 'var(--cyan-4)',
          5: 'var(--cyan-5)',
          6: 'var(--cyan-6)',
          7: 'var(--cyan-7)',
          8: 'var(--cyan-8)',
          9: 'var(--cyan-9)',
          10: 'var(--cyan-10)',
          11: 'var(--cyan-11)',
          12: 'var(--cyan-12)',
        },
        teal: {
          1: 'var(--teal-1)',
          2: 'var(--teal-2)',
          3: 'var(--teal-3)',
          4: 'var(--teal-4)',
          5: 'var(--teal-5)',
          6: 'var(--teal-6)',
          7: 'var(--teal-7)',
          8: 'var(--teal-8)',
          9: 'var(--teal-9)',
          10: 'var(--teal-10)',
          11: 'var(--teal-11)',
          12: 'var(--teal-12)',
        },
        jade: {
          1: 'var(--jade-1)',
          2: 'var(--jade-2)',
          3: 'var(--jade-3)',
          4: 'var(--jade-4)',
          5: 'var(--jade-5)',
          6: 'var(--jade-6)',
          7: 'var(--jade-7)',
          8: 'var(--jade-8)',
          9: 'var(--jade-9)',
          10: 'var(--jade-10)',
          11: 'var(--jade-11)',
          12: 'var(--jade-12)',
        },
        green: {
          1: 'var(--green-1)',
          2: 'var(--green-2)',
          3: 'var(--green-3)',
          4: 'var(--green-4)',
          5: 'var(--green-5)',
          6: 'var(--green-6)',
          7: 'var(--green-7)',
          8: 'var(--green-8)',
          9: 'var(--green-9)',
          10: 'var(--green-10)',
          11: 'var(--green-11)',
          12: 'var(--green-12)',
        },
        grass: {
          1: 'var(--grass-1)',
          2: 'var(--grass-2)',
          3: 'var(--grass-3)',
          4: 'var(--grass-4)',
          5: 'var(--grass-5)',
          6: 'var(--grass-6)',
          7: 'var(--grass-7)',
          8: 'var(--grass-8)',
          9: 'var(--grass-9)',
          10: 'var(--grass-10)',
          11: 'var(--grass-11)',
          12: 'var(--grass-12)',
        },
        lime: {
          1: 'var(--lime-1)',
          2: 'var(--lime-2)',
          3: 'var(--lime-3)',
          4: 'var(--lime-4)',
          5: 'var(--lime-5)',
          6: 'var(--lime-6)',
          7: 'var(--lime-7)',
          8: 'var(--lime-8)',
          9: 'var(--lime-9)',
          10: 'var(--lime-10)',
          11: 'var(--lime-11)',
          12: 'var(--lime-12)',
        },
        mint: {
          1: 'var(--mint-1)',
          2: 'var(--mint-2)',
          3: 'var(--mint-3)',
          4: 'var(--mint-4)',
          5: 'var(--mint-5)',
          6: 'var(--mint-6)',
          7: 'var(--mint-7)',
          8: 'var(--mint-8)',
          9: 'var(--mint-9)',
          10: 'var(--mint-10)',
          11: 'var(--mint-11)',
          12: 'var(--mint-12)',
        },
        sky: {
          1: 'var(--sky-1)',
          2: 'var(--sky-2)',
          3: 'var(--sky-3)',
          4: 'var(--sky-4)',
          5: 'var(--sky-5)',
          6: 'var(--sky-6)',
          7: 'var(--sky-7)',
          8: 'var(--sky-8)',
          9: 'var(--sky-9)',
          10: 'var(--sky-10)',
          11: 'var(--sky-11)',
          12: 'var(--sky-12)',
        },

        violet: {
          1: 'var(--violet-1)',
          2: 'var(--violet-2)',
          3: 'var(--violet-3)',
          4: 'var(--violet-4)',
          5: 'var(--violet-5)',
          6: 'var(--violet-6)',
          7: 'var(--violet-7)',
          8: 'var(--violet-8)',
          9: 'var(--violet-9)',
          10: 'var(--violet-10)',
          11: 'var(--violet-11)',
          12: 'var(--violet-12)',
          a1: 'var(--violet-a1)',
          a2: 'var(--violet-a2)',
          a3: 'var(--violet-a3)',
          a4: 'var(--violet-a4)',
          a5: 'var(--violet-a5)',
          a6: 'var(--violet-a6)',
          a7: 'var(--violet-a7)',
          a8: 'var(--violet-a8)',
          a9: 'var(--violet-a9)',
          a10: 'var(--violet-a10)',
          a11: 'var(--violet-a11)',
          a12: 'var(--violet-a12)',
          a13: 'var(--violet-a13)',
          contrast: 'var(--violet-contrast)',
        },
        gray: {
          1: 'var(--gray-1)',
          2: 'var(--gray-2)',
          3: 'var(--gray-3)',
          4: 'var(--gray-4)',
          5: 'var(--gray-5)',
          6: 'var(--gray-6)',
          7: 'var(--gray-7)',
          8: 'var(--gray-8)',
          9: 'var(--gray-9)',
          10: 'var(--gray-10)',
          11: 'var(--gray-11)',
          12: 'var(--gray-12)',
          a1: 'var(--gray-a1)',
          a2: 'var(--gray-a2)',
          a3: 'var(--gray-a3)',
          a4: 'var(--gray-a4)',
          a5: 'var(--gray-a5)',
          a6: 'var(--gray-a6)',
          a7: 'var(--gray-a7)',
          a8: 'var(--gray-a8)',
          a9: 'var(--gray-a9)',
          a10: 'var(--gray-a10)',
          a11: 'var(--gray-a11)',
          a12: 'var(--gray-a12)',
          contrast: 'var(--gray-contrast)',
          surface: 'var(--gray-surface)',
          indicator: 'var(--gray-indicator)',
          track: 'var(--gray-track)',
        },
      },
      fontFamily: {
        sans: ['PT Sans', 'sans-serif'],
      },
      fontSize: {
        xs: '.8rem',
        sm: '.9rem',
        base: '1rem',
        lg: '1.1rem',
      },
      borderRadius: {
        DEFAULT: '.6rem',
      },
      keyframes: {
        overlayShow: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        contentShow: {
          from: {
            opacity: '0',
            transform: 'translate(-50%, -48%) scale(0.96)',
          },
          to: { opacity: '1', transform: 'translate(-50%, -50%) scale(1)' },
        },
        slideDown: {
          from: { height: '0px' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        slideUp: {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0px' },
        },
        slideIn: {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        slideOut: {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(100%)' },
        },
      },
      animation: {
        slideDown: 'slideDown 300ms cubic-bezier(0.87, 0, 0.13, 1)',
        slideUp: 'slideUp 300ms cubic-bezier(0.87, 0, 0.13, 1)',
        overlayShow: 'overlayShow 150ms cubic-bezier(0.16, 1, 0.3, 1)',
        contentShow: 'contentShow 150ms cubic-bezier(0.16, 1, 0.3, 1)',
        slideIn: 'slideIn 300ms ease-in-out',
        slideOut: 'slideOut 300ms ease-in-out',
      },
    },
  },
  plugins: [],
};

export default config;
